### ISSUE TITLE
building Meteor packages... Error: spawn meteor ENOENT at exports._errnoException (util.js:1050:11)

### ISSUE THREAD

**Issue by Falieson** [jcoreio/crater#141]
@jedwards1211 go ahead and close this, posting for anyone else searching the issues
# STR
$ git clone git@github.com:jcoreio/crater.git
$ cd crater
$ npm run start

# Fixed by
going to https://www.meteor.com/install
the issue is not having meteor installed

# Error-log - you'll get an error like this
```
~/C/P/O/F/crater ❯❯❯ npm run start                                                                                      master

> crater@2.0.0 start /Users/falieson/Code/jcoreio-crater
> babel-node scripts/start.js

installing meteor/node_modules...
meteor@ /Users/falieson/Code/jcoreio-crater/meteor
└─┬ babel-runtime@6.23.0
  ├── core-js@2.4.1
  └── regenerator-runtime@0.10.3

npm WARN meteor@ No description
npm WARN meteor@ No repository field.
npm WARN meteor@ No license field.
building Meteor packages...
Error: spawn meteor ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by jedwards1211** [comment]
Heh, I didn't think to mention that meteor is still required in the readme :)

**Comment by Falieson** [comment]
@jedwards1211 I've been using crater for a couple interview HW assignments, and sharing the projects with some friends. Only after doing a fresh install of OSX last weekend did I realize they may not have known to install these things to get the repo working.
