### ISSUE TITLE
webpack resolve aliases

### ISSUE THREAD

**Issue by Falieson** [jcoreio/crater#148]
I've changed `webapck/webpack.config.dev.js` by adding the following resolve.alias:
```
const config = {
  context: root,
  devtool: 'eval',
  entry: [
    './src/client/index.js',
    'react-hot-loader/patch',
    'webpack-hot-middleware/client',
  ],
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
      "client": root+"/src/client",
      "server": root+"/src/server",
      "universal": root+"/src/universal",
      "redux": root+"/src/universal/redux",
      "routes": root+"/src/universal/routes"
    }
  },
```

and when I build I get the error
```
ERROR in ./src/client/makeStore.js
Module not found: Error: Can't resolve 'redux' in '/Users/florian/Code/Public/PlanetX/planetx-boilerplate-crater/src/client'
 @ ./src/client/makeStore.js 7:13-29
 @ ./src/client/index.js
 @ multi ./src/client/index.js react-hot-loader/patch webpack-hot-middleware/client

ERROR in ./~/react-redux/es/connect/mapDispatchToProps.js
Module not found: Error: Can't resolve 'redux' in '/Users/florian/Code/Public/PlanetX/planetx-boilerplate-crater/node_modules/react-redux/es/connect'
 @ ./~/react-redux/es/connect/mapDispatchToProps.js 1:0-43
```

no other changes - any ideas here?

btw @jedwards1211 do you want to be in touch over skype/gtalk? my address is hireflorian@gmail.com

**Comment by jedwards1211** [comment]
Yeah, when `react-redux` `require`s `redux`, your webpack alias changes that to `src/universal/redux`, and since there's no `index.js` in that folder, it can't resolve it.  But even if you had an `index.js` in that folder, it would break it because you'll always need `require('redux')` to resolve to `node_modules/redux`.  So you'll have to get rid of that alias and import from `universal/redux/...` instead.

Honestly I don't get on skype/gtalk much but feel free to email me at jedwards@fastmail.com with questions that are outside the scope of this issue tracker.  I can't always respond quickly though...I take on too many programming projects :)

**Comment by Falieson** [comment]
of course!! Sorry about the dumb alias question! thank you

**Comment by Falieson** [comment]
@jedwards1211 am I going to need to add this to `webpack.config.prod` and `config.dev` as well?
Would you like me to figure out a `webpack.config.shared.js` to dry up the 3 webpack files? (we do something similar to this at my work)

**Comment by Falieson** [comment]
@jedwards1211 I gave DRYing it up a shot but I haven't figured out how to get the aliases to work for the prod webpack. 
**DRYd webpack draft**
https://gist.github.com/Falieson/15f1468923c700e205853df65292ad6d

**routes/home.js**
```
// @flow
import type { Store } from 'universal/flowtypes/redux'

import App from 'universal/components/App'

// eslint-disable-next-line no-unused-vars
export default (store: Store): Object => ({
  path      : '/',
  indexRoute: {
    component: App
  }
})
```

**`yarn test:prod` fails with**
```
ERROR in ./src/universal/routes/home.js
Module not found: Error: Can't resolve 'universal/components/App' in '/Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/routes'
resolve 'universal/components/App' in '/Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/routes'
  Parsed request is a module
  using description file: /Users/florian/Code/Public/PlanetX/boilerplate-crater/package.json (relative path: ./src/universal/routes)
  after using description file: /Users/florian/Code/Public/PlanetX/boilerplate-crater/package.json (relative path: ./src/universal/routes)
    resolve as module
      /Users/florian/Code/Public/PlanetX/node_modules doesn't exist or is not a directory
      /Users/florian/Code/Public/node_modules doesn't exist or is not a directory
      /Users/florian/Code/node_modules doesn't exist or is not a directory
      /Users/florian/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/routes/node_modules doesn't exist or is not a directory
      /Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/node_modules doesn't exist or is not a directory
      /Users/florian/Code/Public/PlanetX/boilerplate-crater/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules
        using description file: /Users/florian/Code/Public/PlanetX/boilerplate-crater/package.json (relative path: ./node_modules)
        after using description file: /Users/florian/Code/Public/PlanetX/boilerplate-crater/package.json (relative path: ./node_modules)
          using description file: /Users/florian/Code/Public/PlanetX/boilerplate-crater/package.json (relative path: ./node_modules/universal/components/App)
            as directory
              /Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App doesn't exist
            no extension
              /Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App doesn't exist
            .js
              /Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App.js doesn't exist
            .json
              /Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App.json doesn't exist
[/Users/florian/Code/Public/PlanetX/node_modules]
[/Users/florian/Code/Public/node_modules]
[/Users/florian/Code/node_modules]
[/Users/florian/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/routes/node_modules]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/src/universal/node_modules]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/src/node_modules]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App.js]
[/Users/florian/Code/Public/PlanetX/boilerplate-crater/node_modules/universal/components/App.json]
 @ ./src/universal/routes/home.js 7:11-46
 @ ./src/universal/routes/index.js
 @ ./src/server/createSSR.js
 @ ./src/server/index.js
Version: webpack 2.4.1
```

**Comment by jedwards1211** [comment]
@Falieson heh, this is where it gets complicated...

*most* of the prod code running on the server is webpacked, but some of it is *not*.  There are many files people may want to require in their code like `.sass` files, images, etc, that are much better supported by webpack loaders than babel plugins.  Maybe it would be better to just bundle all of the server-side code with webpack.

There is also [`babel-plugin-webpack-loaders`](https://github.com/istarkov/babel-plugin-webpack-loaders), which last I checked was very experimental, but maybe now it's pretty robust.  You may want to try that at some point, though I think it would only use webpack's loaders, not its aliasing.

So I think you'll have to use another babel plugin to alias all imports and requires that run outside of the webpack bundle on the server side.  Maybe try [babel-plugin-webpack-alias](https://www.npmjs.com/package/babel-plugin-webpack-alias), though I haven't tested it myself.

If you figure out something that works, feel free to make a PR!  I've looked into this in the past, but last time I did it was still hairy enough I didn't think it was practical for everyone.

**Comment by jedwards1211** [comment]
@Falieson I'm on the fence about having shared webpack config in this skeleton, because the three configs are already sufficiently different that it can be confusing to understand what the actual config is if each one is extending a shared config.  [`webpack-merge`](https://github.com/survivejs/webpack-merge) is a pretty good thing to use if you are going to share config though.

If you come up with a PR for aliases, I think it would suffice to just put the aliases in their own module, and import it into each webpack config, instead of having a full-blown shared webpack config.  I'm trying to keep everything in this project as easy to understand as I can.

**Comment by Falieson** [comment]
@jedwards1211 thanks, I'll check out webpack-merge

In the past I've had a lot of success with babel way of doing aliasing, I was hoping with webpack2 resolve.alias that the plugins were a legacy method.

I was curious if you wanted this code in a PR, I wanted to try it anyways for the personal flavor of crater I'm working on. This is the commit that's equivalent to the gist I put in the OP (original post)
https://github.com/Falieson/planetx-boilerplate-crater/commit/0422bdd8d0cda8d671297c1e7bcc2797c08d2840#commitcomment-21951067

**Comment by Falieson** [comment]
Revealed to me by doing running flow  - I guess I still have to do aliasing with babel since that's the parser its using.

```
src/universal/routes/home.js:2
  2: import type { Store } from 'universal/flowtypes/redux'
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ universal/flowtypes/redux. Required module not found

src/universal/routes/home.js:4
  4: import App from 'universal/components/App'
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ universal/components/App. Required module not found

src/universal/routes/index.js:3
  3: import type { Store } from 'universal/flowtypes/redux'
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ universal/flowtypes/redux. Required module not found
```

**Comment by jedwards1211** [comment]
@Falieson right. Actually, assuming webpack resolves the imports and requires after babel transpilation, probably you can just use a babel plugin and leave the webpack config as it is

**Comment by Falieson** [comment]
@jedwards1211 seems like you were right on the money with `babel-plugin-webpack-alias` (I tried just using `babel-plugin-module-resolver` and that didn't do it). Additionally to do aliases (for other readers), I needed to also add the alias paths to my .flowconfig like

**.flowconfig**
```
[options]
module.name_mapper='^universal' ->'<PROJECT_ROOT>/src/universal'
```
