### ISSUE TITLE
create flag to turn of full SSR in production

### ISSUE THREAD

**Issue by jedwards1211** [jcoreio/crater#62]
In #61 @darkadept asked how to turn off SSR (i.e. only render the basic `<html>` shell and do everything else on the client).  It's not completely trivial, so I'll be making a PR in a moment

**Comment by jedwards1211** [comment]
@darkadept okay, now there's a section in the README about turning off SSR in production.  Thanks for bringing this up!

**Comment by darkadept** [comment]
Awesome, thanks! I understand the reasons why SSR is useful, but if you're creating an app for a smaller user base and use many 3rd-party packages that don't support SSR this will be wonderful.
