### ISSUE TITLE
Redux-thunk doesn't work in production (SSR)

### ISSUE THREAD

**Issue by darkadept** [jcoreio/crater#75]
It doesn't work to dispatch thunk actions in production SSR. The following error occurs:

`Error: Actions must be plain objects. Use custom middleware for async actions.`.

From what I can tell it's because the `makeStore.js` is never called in production SSR (`createSSR.js`). The store is created with:
`const store = createStore(makeReducer(), iMap())`
Middlewares are not applied during SSR.

**Comment by jedwards1211** [comment]
Good point, we could use `makeStore` on both server and client side and wrap application of client-specific middlewares in `if (Meteor.isClient)` blocks.
