### ISSUE TITLE
When DISABLE_FULL_SSR is enabled, the text 'false' flashes on page reload.

### ISSUE THREAD

**Issue by darkadept** [jcoreio/crater#77]
If you have `DISABLE_FULL_SSR` enabled and you refresh the page (aka initial page load) the word "false" flashes briefly.

The reason is this code (line 25 Html.js):
```
    const root = PROD && !process.env.DISABLE_FULL_SSR && renderToString(
      <Provider store={store}>
        <RouterContext {...renderProps} />
      </Provider>
    )
```

I've replaced it with this:
```
    let root = renderToString(<div/>);
    if (PROD && !process.env.DISABLE_FULL_SSR) {
      const root = renderToString(
          <Provider store={store}>
            <RouterContext {...renderProps} />
          </Provider>
        )
    }
```

**Comment by jedwards1211** [comment]
Yeah, I saw this, but I think I fixed it in https://github.com/jcoreio/crater/commit/89834582fbb41c54526df43b738d62ce68b1c9e2.
Is it still an issue with the latest master?  I know it can be tough merging in changes to this skeleton...

**Comment by jedwards1211** [comment]
I'm closing this.  If you're able to repro with master I'll reopen it
