### ISSUE TITLE
meteor server log

### ISSUE THREAD

**Issue by java99** [jcoreio/crater#82]
How can i see server logs (e.g. console.log from server.js) ?

Thanks
java99

**Comment by jedwards1211** [comment]
@java99 are they not showing up in the console?  They should, if not, it's a bug

**Comment by java99** [comment]
no 

i run "npm start" and wait for console logs. 

btw: What can I do to update over my server files like (src/server/server.js) ?

**Comment by jedwards1211** [comment]
oh you mean nothing shows in the console?

> btw: What can I do to update over my server files like (src/server/server.js) ?

I'm not sure I understand, do you mean how can you pull updates from this repo while preserving your own code?  You can `git pull origin master` (assuming origin points to this repo).  It can be a bit awkward though, there will likely be conflicts if you've made your own changes, and the best you can do is fix the conflicts by hand.

**Comment by java99** [comment]
i added   import './server.js'  to my src/server/index.js . Now its updating in there. 

having more issues now :) - will check whether console.log is showing in terminal.

**Comment by java99** [comment]
`console.log("STARTUP");`
```

  build [===========         ] 54%STARTUP
App is listening on http://0.0.0.0:3000
Build completed in 12.344s

webpack built 2387713e4f77d36e63e8 in 12721ms
```

working. thanks!
