### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by shijunti19** [jcoreio/crater#84]
How to upgrade  METEOR@1.4.2

**Comment by jedwards1211** [comment]
The `meteor` folder is a normal meteor project so you can run all the usual meteor commands in it.
Just do
```
cd meteor
meteor update
```
I'll set off a build with the latest meteor packages to make sure it all works.

**Comment by jedwards1211** [comment]
Rats, they've done something janky with node modules for babel-runtime in 1.4.2 and it doesn't work yet.  Let me look into it...

**Comment by jedwards1211** [comment]
Okay, pull from the `master` branch and it should work now.
