### ISSUE TITLE
Can't resolve 'babel' (webpack2 branch)

### ISSUE THREAD

**Issue by coniel** [jcoreio/crater#86]
I'm getting the following error when trying out the webpack2 branch (master branch works fine):

```
ERROR in multi main
Module not found: Error: Can't resolve 'babel' in '/Users/oscarconiel1/Sites/coniel/sis'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel'.
 @ multi main
```

**Comment by jedwards1211** [comment]
ah, luckily that's a very clear error message.  I'm on it.  Thanks!

**Comment by jedwards1211** [comment]
btw, if you need a workaround until I fix this, you should be able to use webpack-2.1.0-beta.25 or earlier
(see https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26)

**Comment by jedwards1211** [comment]
okay, this is fixed!
